//
// Created by dimitrisgan on 28/2/2019.
//

#ifndef SERVER_ERRORSCODES_H
#define SERVER_ERRORSCODES_H


typedef enum ERRORCODE { OK=0,
    UNKNOWN_CMDARGUMENT=1,  //unknown flag at cmd arguments
    INPUT_DIR_NOT_EXIST,
    MIRROR_DIR_ALREADY_EXIST,
    FILE_ID_ALREADY_EXIST,
    DELETING_FILE,
    INVALID_INDEX_IN_MYSTRING,
    CREATING_NAMED_PIPE_FILE,
    OPENING_NAMED_PIPE_FILE,
    WRITING_IN_NAMED_PIPE,
    READING_IN_NAMED_PIPE,
    TIMEOUT,
    LINKED_LIST,
    NOT_VALID_TRSANSACTION,
    INSERTION,
    DELETION,
    NOT_VALID_DATE,
    NOT_VALID_TIME,
    FILE_ACCESS  //could NOT open a file
} ERRORCODE;




#endif //SERVER_ERRORSCODES_H
